### PR TITLE
Chained tokens

### PR DESCRIPTION
**Pull request by cristiandouce**
Add support for replacement's like the following:

``` js
var user = { name: { first: 'Tobi', last: 'Goldman' } };

t('{name.first} is from {name.last}\'s family.', user);

```

### CODE REVIEW

**Comment by Swatinem** [comment]
Using to-function may be a better idea here.

**Comment by cristiandouce** [comment]
@Swatinem What extra feature of component/to-function would you use? I did it like this to keep the component lightweight. But if I got proof that there might be some other use in the future I would change it.

**Comment by Swatinem** [comment]
Ah nevermind, to-function actually uses the same code internally (https://github.com/component/to-function/blob/master/index.js#L72) so there is really nothing to be gained there.
Sorry for the inconvenience.

**Comment by cristiandouce** [comment]
I know. I did it that way :octopus:

**Pull request merged**
